# Generated by Django 5.0.6 on 2024-12-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsheets', '0001_initial'),
        ('users', '0004_commschannel_verificationcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commschannel',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commschannel',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comms_channels_verified', to=settings.AUTH_USER_MODEL),
        ),

    ]
