# Generated by Django 5.0.6 on 2024-08-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_role_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='Settings for this organisation'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('J', 'Judge'), ('R', 'Reader'), ('O', 'Organiser'), ('A', 'Administrator'), ('M', 'Event Manager')], max_length=1),
        ),
    ]
