# Generated by Django 5.0.6 on 2024-11-18 11:39

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models

def copy_values(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    for user in CustomUser.objects.all():
        user.subscribe_news = user.subscribed
        user.unsubscribe_news = user.unsubscribed
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('testsheets', '0001_initial'),
        ('users', '0003_alter_organisation_settings_alter_role_role_type'),
        ('web', '0003_submission_main_media_submission_preview_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='subscribed',
            new_name='subscribe_news',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='unsubscribed',
            new_name='unsubscribe_news',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='person',
            name='mobile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='keycloak_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        # migrations.AddField(
        #     model_name='organisation',
        #     name='default_authority',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_issuer', to='testsheets.issuer'),
        # ),
        migrations.AddField(
            model_name='role',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='current_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.dataqualitylog'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('J', 'Editor'), ('R', 'Reader'), ('O', 'Organiser'), ('A', 'Administrator'), ('M', 'Event Manager')], max_length=1),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['user', 'active', 'role_type'], name='users_role_user_id_e33e41_idx'),
        ),
        migrations.AddField(
            model_name='commschannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.commschannel'),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.commschannel'),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
