# Generated by Django 5.0.6 on 2024-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('J', 'Editor'), ('R', 'Reader'), ('O', 'Organiser'), ('A', 'Administrator'), ('M', 'Event Manager')], max_length=1),
        ),
    ]
